
name: Work 2 Emilio 
on:
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: |
        echo "impresion 1"
        echo "impresion 2"
        echo "impresion 3"



